In [14]:
import numpy as np
import pandas as pd

In [42]:
#var to count the data
sub = []
problem_result = np.zeros((4,5))
problem_alltime = []

class Submission:
    
    def __init__(self,problem,status,time):
        self.problem = problem
        self.status = status
        self.time = time
    
    def problem_sta_num(self):
        for i in range(4):
            if(self.problem == i+1):
                problem_result[i][self.status_type()] += 1
        return problem_result
    
    def status_type(self):
        if(self.status == 'Accepted'):
            return 0
        elif(self.status == 'Compile Error'):
            return 1
        elif(self.status == 'Runtime Error'):
            return 2
        elif(self.status == 'Wrong Answer'):
            return 3
        elif(self.status == 'Time Limit Exceed'):
            return 4
    
    def time
    
    

In [52]:
df = pd.read_csv('midterm.csv')

SubmissionID  StudentID  Problem         Status  Score  CodeLength  \
0         43629          7        4  Runtime Error      0         879   
1         43628         31        3  Runtime Error      0         521   
2         43627        106        2   Wrong Answer      0          10   
3         43626        101        4   Wrong Answer      0        2330   

  SubmissionTime  
0       12:20:52  
1       12:20:38  
2       12:20:27  
3       12:20:27

In [43]:
s1 = Submission(1,'Accepted',2)
print(s1.problem_sta_num())

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
###3